### ISSUE TITLE
Freeze & Thaw the JSON

### ISSUE THREAD

**Issue by domtronn** [domtronn/percento.js#5]
So it's all well and good that we can template JSON, but what about when that JSON includes functions? If we had the following config for example

``` js
var config = {
    baseUrl: 'http://foo',
    items: [
        {
            url: '%baseUrl%/users', 
            build: function () { }
        },
        {
            url: '%baseUrl%/dogs',
            build: function () { }
        }
    ]
}
```

And we try to resolve it with itself, we lose those anonymous functions because we're calling `JSON.stringify`.

I was wondering whether we should support Freezing/Thawing the JSON by default, and merging the results... For example...

``` js
var freeze = original
// resolve the original JSON
var thaw = merge(original, freeze);

return thaw
```

Thoughts?

**Comment by subsidel** [comment]
Only if that merge doesn't mutate the original, but yeah, willing to say that losing the functions is a bug

**Comment by AlexChesters** [comment]
what @subsidel said

**Comment by joeyjojo-zz** [comment]
Except that JSON cannot include functions, what you are talking about is templating javascript.

http://www.json.org/

**Comment by subsidel** [comment]
Actually, that's a good point

**Comment by domtronn** [comment]
Sure, I'm on about templating JavaScript. I have a use case for it which is why I'm raising this as an enhancement.

`JavaScript == JSON == config` [JavaScriptObjectNotation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Normal_objects_and_functions)

**Comment by joeyjojo-zz** [comment]
I am mostly arguing about semantics, which is that you shouldn't be calling this JSON because it isn't.

I think there are 2 different questions:

1: What do you want this library to do? In this case adding this functionality may make sense
2: Should I use javascript to configure my app? IMO probably not. I personally don't agree that `Javascript == JSON == config` but thats your decision.
